---
title: "pcs"
author: "Jens Lemb"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```


```{r}
url_data <- "https://www.procyclingstats.com/race/tour-de-france/2023/stage-1"
```

```{r}
url_data %>% 
  read_html()
```

```{r}
css_selector <- "body > div.wrapper > div.content > div.page-content.page-object.default > div.w100 > div.w68.left.mb_w100 > div:nth-child(5) > div:nth-child(1) > table"
```


```{r}
results_data <- url_data %>% 
  read_html() %>% 
  html_element(css = css_selector) %>% 
  html_table()
```


stage profile data
```{r}
url_data <- "https://www.procyclingstats.com/race/tour-de-france/2023/stage-1"


temp_stage <- url_data %>% 
  read_html%>%
  html_element(css="body > div.wrapper > div.content > div.page-content.page-object.default > div.w100 > div.w30.right.mb_w100 > div:nth-child(4) > ul ")%>%
  html_elements("div")%>%
  html_text2()

#get parcour type (info is in class)
temp_stage[16] <- url_data %>% 
  read_html%>%
  html_element(css="body > div.wrapper > div.content > div.page-content.page-object.default > div.w100 > div.w30.right.mb_w100 > div:nth-child(4) > ul > li:nth-child(8) > div:nth-child(2) > span")%>%
  html_attr("class")

#create dataframe and convert to wide
vars <- temp_stage[seq(1,length(temp_stage),2)]
values <- temp_stage[seq(0,length(temp_stage),2)]
stage_data <- data.frame(vars,values)
stage_data <- spread(stage_data, key = vars, value = values)

```


```{r}
for(i in 2:21){
  url_data <- paste0("https://www.procyclingstats.com/race/tour-de-france/2023/stage-", i)
  
  temp_stage <- url_data %>% 
  read_html%>%
  html_element(css="body > div.wrapper > div.content > div.page-content.page-object.default > div.w100 > div.w30.right.mb_w100 > div:nth-child(4) > ul ")%>%
  html_elements("div")%>%
  html_text2()
  
  #get parcour type (info is in class)
  temp_stage[16] <- url_data %>% 
  read_html%>%
  html_element(css="body > div.wrapper > div.content > div.page-content.page-object.default > div.w100 > div.w30.right.mb_w100 > div:nth-child(4) > ul > li:nth-child(8) > div:nth-child(2) > span")%>%
  html_attr("class")

#create dataframe and convert to wide
vars <- temp_stage[seq(1,length(temp_stage),2)]
values <- temp_stage[seq(0,length(temp_stage),2)]
stage_data_temp <- data.frame(vars,values)
stage_data_temp <- spread(stage_data_temp, key = vars, value = values)
  
  stage_data <- rbind(stage_data, stage_data_temp)
  
  print(paste0("Scraping stage ", i))  
}
```

```{r}
#data cleanup
library(janitor)

stage_data<- clean_names(stage_data)

stage_data$avg_speed_winner <- as.numeric(str_remove(stage_data$avg_speed_winner, "km/h"))
stage_data$distance <- as.numeric(str_remove(stage_data$distance, "km"))
stage_data$avg_temperature <- as.numeric(str_remove(stage_data$avg_temperature, "°C"))
stage_data$stage_n <- seq(1,21,1)
stage_data$profile_score <- as.numeric(stage_data$profile_score)  
stage_data$startlist_quality_score <- as.numeric(stage_data$startlist_quality_score)  
stage_data$vert_meters <- as.numeric(stage_data$vert_meters)  

stage_data <- stage_data %>%
    mutate(parcours_type = case_when(parcours_type=="icon profile p3"~"hills uphill finish",
            parcours_type=="icon profile p2"~"hills flat finish",
            parcours_type=="icon profile p1"~"flat",
            parcours_type=="icon profile p4"~"mountains flat finish",
            parcours_type=="icon profile p5"~"mountains uphill finish",
            TRUE~""))

stage_data$stage_type <- ifelse(stage_data$stage_n!=16, "rr", "itt")


stage_data <- stage_data %>%
    mutate(win_type = case_when(str_detect(won_how, "solo")==TRUE~"solo",
                                str_detect(won_how, "large")==TRUE~"large group sprint",
                                str_detect(won_how, "small")==TRUE~"small group sprint",
                                str_detect(won_how, "riders")==TRUE~"small group sprint",
                                TRUE~"other"))

stage_data$km_solo <- ifelse(stage_data$win_type=="solo", as.numeric(str_remove_all(stage_data$won_how, "[[:alpha:]-?!]")),
                             NA)
#manual id vars
stage_data$race_year <- "tdf2023"
stage_data$race <- "tdf"
stage_data$year <- 2023
```

```{r}
library(readr)
write.csv(stage_data, "C:/Users/LEMB/Desktop/tdf2023.csv",row.names = FALSE)
```







idéer til andre variable:
- n kat. 1-5 og HC stigninger
- dist fra sidste stigning til mål
- post-restday indicator
- n prior racedays (stage number)

- if solo win: distance went solo
- n seconds after first place
- top 1,3,5,10,15 indicators

